### ISSUE TITLE
Budget report [tab on grant page]

### ISSUE THREAD

**Issue by kenschnarrs** [DaronAdams/grant-monitor#39]
* On an individual grant's page, have a tab for "budget".
* Clicking this button would take you to the budget page.

<img width="542" alt="image" src="https://github.com/DaronAdams/grant-monitor/assets/45466516/261918b9-4cfa-4bca-bd37-a4c2fc2feadd">

<img width="678" alt="image" src="https://github.com/DaronAdams/grant-monitor/assets/45466516/4c546ac3-6009-4fe9-a974-a3c162290299">

**Comment by cdrumfelt** [comment]
waiting to proceed until transactions are implemented
